#!/bin/bash

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop release hotfix)
fi

BRANCH_NAME=$(git symbolic-ref --short HEAD)
BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$")
BRANCH_IN_COMMIT=$(grep -c "$BRANCH_NAME" $1)

if [ -n $BRANCH_NAME ] && ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then 
  #특수문자 이스케이프 처리 필요 (특문 오류시 구문 추가)
  BRANCH_NAME=`echo $BRANCH_NAME | sed 's/[/|~|$|*|&|#|!]/\\\&/g'`
  sed -i.bak -e "1s/^/[$BRANCH_NAME] /" $1
fi