version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1101.1
    - 0.1101.2
    - 0.1101.4
    - 0.1102.0
    - 0.1102.1
    - 0.1102.2
    - 0.1102.3
    - 0.1102.4
    - 0.1102.5
    - 0.1102.6
    - 0.1102.7
    - 0.1102.8
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.2.0
    - 6.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
