language: node_js

os: linux

node_js:
- "10"

cache:
  directories:
    - node_modules

# Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# Use APT Addon to install Chrome
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

# 알림 설정
# see: https://docs.travis-ci.com/user/notifications#configuring-email-notifications
notifications:
  email:
    recipients:
      - hkroh.nonoll@gmail.com
    # always / never / change
    # see: https://docs.travis-ci.com/user/notifications/#changing-notification-frequency
    on_success: never
    on_failure: always

# Job Lifecycle
# 1.  OPTIONAL Install apt addons
# 2.  OPTIONAL Install cache components
# 3.  before_install
# 4.  install
# 5.  before_script
# 6.  script
# 7.  OPTIONAL before_cache (for cleaning up cache)
# 8.  after_success or after_failure
# 9.  OPTIONAL before_deploy
# 10. OPTIONAL deploy
# 11. OPTIONAL after_deploy
# 12. after_script
# see: https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

install:
  - npm install

# before_script:
  # see: https://github.com/yelloxing/image2D/issues/15#issuecomment-521853672
  # - sh -e /etc/init.d/xvfb start

services:
  - xvfb

script:
  - npm run build
  - npm run jsdoc
  - npm run test:travis

branches:
  only:
    - master
    # for release, tags
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

deploy:
  # 배포 설정 - npm module
  - provider: npm
    edge: true
    skip_cleanup: true
    email: $NPM_PUBLISH_EMAIL
    api_key: $NPM_PUBLISH_TOKEN
    src: ./dist/code-snippet
    access: public
    on:
      # tags: true
      # repo: nonoll/code-snippet
      # branch: master
      repo: nonoll/code-snippet
      all_branches: true
      # see: https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$

  # 배포 설정 - github page
  - provider: pages
    edge: true
    skip_cleanup: true
    github-token: $GITHUB_CODE_SNIPPET_TOKEN
    local_dir: docs
    on:
      branch: master
