language: node_js

os: linux

node_js:
- "10"

cache:
  directories:
    - node_modules

# 알림 설정
# see: https://docs.travis-ci.com/user/notifications#configuring-email-notifications
notifications:
  email:
    recipients:
      - hkroh.nonoll@gmail.com
    on_success: always
    on_failure: always

# Job Lifecycle
# 1.  OPTIONAL Install apt addons
# 2.  OPTIONAL Install cache components
# 3.  before_install
# 4.  install
# 5.  before_script
# 6.  script
# 7.  OPTIONAL before_cache (for cleaning up cache)
# 8.  after_success or after_failure
# 9.  OPTIONAL before_deploy
# 10. OPTIONAL deploy
# 11. OPTIONAL after_deploy
# 12. after_script
# see: https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle


install:
  - npm install

script:
  - npm run build
  - npm run jsdoc


deploy:
  # 배포 설정 - github page
  # - provider: pages
  #   github-token: $GITHUB_CODE_SNIPPET_TOKEN
  #   local_dir: docs
  #   on:
  #     branch: master

  # 배포 설정 - npm module
  - provider: script
    script: "cp .npmrc.template $HOME/.npmrc && npm publish ./dist/code-snippet --access=public"
    on:
      branch: master
