# see: https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          dependency_type: "production" # production / development / all
          update_type: "semver:minor"
    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "nonoll"
    default_labels:
      - "dependabot-update"